/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../services/api`; params?: Router.UnknownInputParams; } | { pathname: `/../../babel.config`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/setups` | `/setups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/investments` | `/investments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reports` | `/reports`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/../../babel.config`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/setups` | `/setups`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/investments` | `/investments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reports` | `/reports`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../services/api${`?${string}` | `#${string}` | ''}` | `/../../babel.config${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/setups${`?${string}` | `#${string}` | ''}` | `/setups${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/investments${`?${string}` | `#${string}` | ''}` | `/investments${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/reports${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../services/api`; params?: Router.UnknownInputParams; } | { pathname: `/../../babel.config`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/setups` | `/setups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/investments` | `/investments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/reports` | `/reports`; params?: Router.UnknownInputParams; };
    }
  }
}
